name: flutter_ytdlp_plugin
description: A Flutter plugin for YouTube video streaming using yt-dlp. Supports fetching video formats, related videos, and more.
version: 2.0.0
homepage: https://github.com/golanpiyush/flutter_ytdlp_plugin
repository: https://github.com/golanpiyush/flutter_ytdlp_plugin
issue_tracker: https://github.com/golanpiyush/flutter_ytdlp_plugin/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # integration_test:
  test: ^1.25.15
  mockito:

flutter:
  plugin:
    platforms:
      android:
        package: com.golanpiyush.flutter_ytdlp_plugin
        pluginClass: FlutterYtdlpPlugin
